#!/usr/bin/env bash
set -euo pipefail

source /usr/lib/bashio/bashio

readonly RUNTIME_DIR="/run/postgresql"

until pg_isready -h "${RUNTIME_DIR}" -p 5432 -U postgres >/dev/null 2>&1; do
  sleep 1
done

/usr/local/bin/provisioning-entrypoint

bashio::log.info "Publishing PostgreSQL service information"
PAYLOAD=$(
  bashio::var.json \
    host "$(hostname)" \
    port "^5432"
)
bashio::services.publish "postgresql" "${PAYLOAD}"

bashio::log.info "PostgreSQL 18 ready"
